# html lang
language: en
# title
title: "Lengux"
# logo
## https://avatars.githubusercontent.com/u/52852249?v=4
logo: /img/logo.png
# avatars
avatars: https://avatars.githubusercontent.com/u/52852249?v=4
#---------------------------
# 全局
# Global
#---------------------------

# main menu navigation
menu:
  首页: /
  # 关于: /about
  # 分类: /categories
  归档: /archives
  友链: /link

# md文章默认
page:
  article: hexo
  intro: hexo new My New Post
  img: https://img1.imgtp.com/2023/11/03/8oj1k5qo.jpg

# 用于浏览器标签的图标
# Icon for browser tab
svg:
  # 代码行复制
  stickies: /img/github.svg
  # 代码行折叠
  hand-index: /img/github.svg


# 播放器 默认true打开、false关闭
musicredio: false

# 本地搜索
search:
  path: search.xml
  field: post
  content: true
  template: themes/lengux/search.xml

# 打字机内容
typewriter: This is a Lengux blog.

# slider 侧栏一言
hitokoto: https://v1.hitokoto.cn/?encode=js&select=%23hitokoto

# banner 名言
famousSaying: "We sat and drank with the sun on our shoulders and felt like free men. We could have
                been tarring the roof of one of our own houses. We were the lords of all creation. As for Andy，he spent
                that break hunkered in the shade，a strange little smile on his face，watching us drink his beer."


# footer版权
# Lengux-github
Lenguxgithub: https://github.com/XUSHAO11/lengux.git
Lenguxname: LengUx

stylesheets:
  - /css/lengux.css

# scripts loaded in the end of the body
scripts:
  - /js/bootstrap.bundle.min.js
  - /js/jquery-2.0.2.min.js
  - /js/lengux.js
  - /js/search.js
  - /js/darkmode-js.min.js
  - /js/dark.js
