# html lang
language: en
# title
title: ""
# logo
## https://avatars.githubusercontent.com/u/52852249?v=4
logo: /img/logo.png
# avatars
avatars: https://avatars.githubusercontent.com/u/52852249?v=4
#---------------------------
# 全局
# Global
#---------------------------

# main menu navigation
menu:
  Home: /
  About: /about
  # Tag: /tag
  # Contact: /contact
  # Category: /category
  Archives: /archives

# 用于浏览器标签的图标
# Icon for browser tab
svg:
  # banner icon
  github: /img/github.svg
  twitter: /img/twitter.svg
  display: /img/display.svg
  # 列表
  list: /img/list.svg
  # 置顶
  rocket: /img/github.svg
  # 代码行复制
  stickies: /img/github.svg
  # banner向下滚动
  arrowdown: /img/github.svg
  # 代码行折叠
  hand-index: /img/github.svg

# 文章一列aListOf 两列two-row
## 默认两列
textSplitting: aListOf

# 播放器 默认true打开、false关闭
musicredio: true

# 本地搜索
search:
  path: search.xml
  field: post
  content: true
  template: themes/lengux/search.xml

# # 主页每页显示文章数
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date
#   pagination_dir: page
# stylesheets loaded in the <head>
stylesheets:
  - /css/lengux.css

# scripts loaded in the end of the body
scripts:
  - /js/bootstrap.bundle.min.js
  - /js/jquery-2.0.2.min.js
  - /js/lengux.js
  # 本地搜索
  - /js/search.js
  # 深色模式
  - /js/darkmode-js.min.js
  - /js/dark.js
