# html lang
language: en
# title
title: "Lengux"
# logo
## https://avatars.githubusercontent.com/u/52852249?v=4
logo: /img/logo.png
# avatars
avatars: https://avatars.githubusercontent.com/u/52852249?v=4
#---------------------------
# 全局
# Global
#---------------------------

# main menu navigation
menu:
  首页: /
  关于: /about
  # 分类: /categories
  归档: /archives
  友链: /link

# md文章默认
page:
  article: hexo # 标签
  intro: hexo new My New Post # 文章摘要
  img: https://img1.imgtp.com/2023/11/03/8oj1k5qo.jpg # 文章缩略图

# 黑夜模式
darkmork: true

# 打字机内容
typewriter: This is a Lengux blog.

# slider
## 侧栏一言
hitokoto: https://v1.hitokoto.cn/?encode=js&select=%23hitokoto
hitokotoIstrue: true
## 侧栏标题
sildertrue: true
silder:
  title: Hey!
  ### 侧栏 about
  about: Austin Kleon (@austinkleon) is awriter who draws. He's thebestselling author of Steal LikeAn Artist and
            other books.Read more一
# silder-link
linkhidden: true
link:
  - links: 1
    title: zixu
    href: https://xushao.top
    avatar: /favicon.ico
# silder-tags
sildertags: true

## 本地搜索
search:
  acquiesce: true # 默认打开
  path: search.xml
  field: post
  content: true
  template: themes/lengux/search.xml
# github
github: https://github.com/XUSHAO11/Lengux
# twitter
twitter: https://tweetdeck.twitter.com/login
# display
display: /

# banner 名言
famousSaying:
  "We sat and drank with the sun on our shoulders and felt like free men. We could have
  been tarring the roof of one of our own houses. We were the lords of all creation. As for Andy，he spent
  that break hunkered in the shade，a strange little smile on his face，watching us drink his beer."


# 代码高亮 codeHighlighting
highlightjs: true

# RSS订阅
rss: /atom.xml

# footer版权
# Lengux-github
Lenguxgithub: https://github.com/XUSHAO11/lengux.git
Lenguxname: Lengux

stylesheets:
  - /css/lengux.css

# scripts loaded in the end of the body
scripts:
  - /js/bootstrap.bundle.min.js
  - /js/jquery-2.0.2.min.js
  - /js/lengux.js
  - /js/dark.js
  - /js/search.js
  - /js/darkmode-js.min.js
