# html lang
language: en
# title
title: "Lengux"
# logo
## https://avatars.githubusercontent.com/u/52852249?v=4
logo: /img/logo.png
# banner-avatars
avatars: /img/banner.png
#---------------------------
# Global
#---------------------------

# main menu navigation
menu:
  home: /
  about: /about
  archives: /archives
  link: /link
  # category: /category
  # tag: /tag
# mdArticleDefault
page:
  article: hexo # tag
  intro: hexo new My New Post # abstractOfArticle
  img: https://img1.imgtp.com/2023/11/03/8oj1k5qo.jpg # articleThumbnail

# nightMode
darkmork: true

# typewriterContent
typewriter: This is a Lengux blog.

# slider
## sidebarWord
hitokoto: https://v1.hitokoto.cn/?encode=js&select=%23hitokoto
hitokotoIstrue: true
## sidebarTitle
sildertrue: true
silder:
  title: Hey!
  ### sideBar about
  about: Austin Kleon (@austinkleon) is awriter who draws. He's thebestselling author of Steal LikeAn Artist and
            other books.Read more一
# silder-link
linkhidden: true
link:
  - links: 1
    title: zixu
    href: https://xushao.top
    avatar: /favicon.ico
# silder-tags
sildertags: true

## localSearch
search:
  acquiesce: true # openByDefault
  path: search.xml
  field: post
  content: true
  template: themes/lengux/search.xml
# github
github: https://github.com/XUSHAO11/Lengux
# twitter
twitter: https://tweetdeck.twitter.com/login
# display
display: /

# banner famousSaying
famousSaying:
  "We sat and drank with the sun on our shoulders and felt like free men. We could have
  been tarring the roof of one of our own houses. We were the lords of all creation. As for Andy，he spent
  that break hunkered in the shade，a strange little smile on his face，watching us drink his beer."


# codeHighlighting
highlightjs: true

# rSS
rss: /atom.xml

# footerCopyright
# Lengux-github
Lenguxgithub: https://github.com/XUSHAO11/lengux.git
Lenguxname: Lengux
forTheRecord: 豫ICP备2022014432号-1

# Algolia Search
# For more information: https://www.algolia.com
algolia_search:
  enable: false
  hits:
    per_page: 5


#archive分页每页显示文章数
archive_generator:
    per_page: 5
#tag分页每页显示文章数
tag_generator:
    per_page: 10
#category分页每页显示文章数
category_generator: 
    per_page: 10

stylesheets:
  - /css/lengux.css

# scripts loaded in the end of the body
scripts:
  - /js/bootstrap.bundle.min.js
  - /js/jquery-2.0.2.min.js
  - /js/lengux.js
  - /js/dark.js
  - /js/search.js
  - /js/darkmode-js.min.js
